
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rizki_
 */
public class kembalian extends javax.swing.JFrame {

    static String getPath() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    SimpleDateFormat tglinput = new SimpleDateFormat("yyyy-MM-dd");
    public String NOPINJAM,NIS,NAMA,KELAS,TELP,KODE,BUKU,JENIS,PENERBIT;
    public String getnopinjam() {
        return NOPINJAM;
    }
    public String getnis() {
        return NIS;
    }
    public String getnama() {
        return NAMA;
    }
    public String getkelas() {
        return KELAS;
    }
    public String gettelp() {
        return TELP;
    }
    public String getkode() {
        return KODE;
    }
    public String getbuku() {
        return BUKU;
    }
    public String getjenis() {
        return JENIS;
    }
    public String getpenerbit() {
        return PENERBIT;
    }
    public void itemPengembalianBuku(){
    tblDaftarPeminjaman tk = new tblDaftarPeminjaman();
     tk.tx = this;
    
    noPinjam.setText(NOPINJAM); 
    nis.setText(NIS);
    namaP.setText(NAMA);
    kelasP.setText(KELAS);
    telponP.setText(TELP);
    kodeBuku.setText(KODE);
    judul.setText(BUKU);
    jenisBuku.setText(JENIS);
    penerbit1.setText(PENERBIT);
}
    


    /**
     * Creates new form kembalian
     */
    public kembalian() {
        
        initComponents();
        load_table();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        //
        int x = layar.width / 2 - this.getSize().width/2;
        int y = layar.height / 2 - this.getSize().height/2;
        //
        this.setLocation(x, y);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomemb = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTnama = new javax.swing.JLabel();
        jb = new javax.swing.JLabel();
        noKembalian = new javax.swing.JTextField();
        namaP = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        judul = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kelasP = new javax.swing.JTextField();
        telponP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        penerbit1 = new javax.swing.JTextField();
        jenisBuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengembalian = new javax.swing.JTable();
        noPinjam = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        kodeBuku = new javax.swing.JTextField();
        tanggalKembali = new com.toedter.calendar.JDateChooser();
        cariPinjam = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jb1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 550));

        nomemb.setBackground(new java.awt.Color(153, 255, 204));
        nomemb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nis");
        nomemb.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        TXTnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTnama.setText("Nama ");
        nomemb.add(TXTnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb.setText("Kode Buku");
        nomemb.add(jb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        nomemb.add(noKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 129, -1));

        namaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPActionPerformed(evt);
            }
        });
        nomemb.add(namaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 218, -1));

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/oke.png"))); // NOI18N
        submit.setText("Simpan");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        nomemb.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        nomemb.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Data Pengembalian Buku ");
        nomemb.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/exit.png"))); // NOI18N
        kembali.setText("kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        nomemb.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        judul.setColumns(20);
        judul.setRows(5);
        jScrollPane2.setViewportView(judul);

        nomemb.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 230, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Penerbit");
        nomemb.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Kembali");
        nomemb.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        nomemb.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/hapus.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        nomemb.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("No Telepon");
        nomemb.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        nomemb.add(kelasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 111, -1));
        nomemb.add(telponP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kelas");
        nomemb.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        nomemb.add(penerbit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 198, -1));
        nomemb.add(jenisBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 174, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Buku");
        nomemb.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        tabelPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Pengembalian", "No Peminjaman", "Nis", "Nama", "Kelas", "No Telp", "Kode Buku", "Judul Buku", "Jenis Buku", "Penerbit", "Tanggal Pengembalian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPengembalian);

        nomemb.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, 980, 130));
        nomemb.add(noPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, -1));
        nomemb.add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, -1));
        nomemb.add(kodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 160, -1));
        nomemb.add(tanggalKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 190, -1));

        cariPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/cari.png"))); // NOI18N
        cariPinjam.setText("Cari");
        cariPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPinjamActionPerformed(evt);
            }
        });
        nomemb.add(cariPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("No Peminjaman");
        nomemb.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("No Pengembalian");
        nomemb.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb1.setText("Judul Buku");
        nomemb.add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        nomemb.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengembalianMouseClicked
        // TODO add your handling code here:
        Date dateView = null;
        int bar = tabelPengembalian.rowAtPoint(evt.getPoint());
        String a = tabelPengembalian.getValueAt(bar, 0).toString();
        noKembalian.setText(a);
        String b = tabelPengembalian.getValueAt(bar, 1).toString();
        noPinjam.setText(b);
        String c = tabelPengembalian.getValueAt(bar, 2).toString();
        nis.setText(c);
        String d = tabelPengembalian.getValueAt(bar, 3).toString();
        namaP.setText(d);
        String e = tabelPengembalian.getValueAt(bar, 4).toString();
        kelasP.setText(e);
        String f = tabelPengembalian.getValueAt(bar, 5).toString();
        telponP.setText(f);
        String g = tabelPengembalian.getValueAt(bar, 6).toString();
        kodeBuku.setText(g);
        String h = tabelPengembalian.getValueAt(bar, 7).toString();
        judul.setText(h);
        String i = tabelPengembalian.getValueAt(bar, 8).toString();
        jenisBuku.setText(i);
        String j = tabelPengembalian.getValueAt(bar, 9).toString();
        penerbit1.setText(j);
        try {
        dateView = tglinput.parse((String) tabelPengembalian.getValueAt(bar, 10));
        } catch (ParseException ex) {
                Logger.getLogger(member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelPengembalianMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE from pengembalian where "
            + "noPengembalian='"+noKembalian.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data telah dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Data gagal dihapus");
        }
        noKembalian.setText("");
        namaP.setText("");
        kelasP.setText("");
        telponP.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit1.setText("");
        tanggalKembali.setDate(new Date());
        load_table();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String tanggal = tglinput.format(tanggalKembali.getDate());
        try {
            String sql ="UPDATE pengembalian SET noPeminjaman = '"+noPinjam.getText()+"', "
                    + "nis = '"+nis.getText()+"', "
                    + "nama = '"+namaP.getText()+"', "
                    + "kelas = '"+kelasP.getText()+"',"
                    + "telepon = '"+telponP.getText()+"', "
                    + "kode= '"+kodeBuku.getText()+"',"
                    + "buku= '"+judul.getText()+"',"
                    + "jenisBuku= '"+jenisBuku.getText()+"',"
                    + "penerbit= '"+penerbit1.getText()+"',"
                    + "tanggalPengembalian= '"+tanggal+"' "
                    + "WHERE noPengembalian = '"+noKembalian.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diupdate");
            //no.requestFocus();
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah");
            }
        noKembalian.setText("");
        noPinjam.setText("");
        nis.setText("");
        namaP.setText("");
        kelasP.setText("");
        telponP.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit1.setText("");
        tanggalKembali.setDate(new Date());
        load_table();
    }//GEN-LAST:event_updateActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        noKembalian.setText("");
        noPinjam.setText("");
        nis.setText("");
        namaP.setText("");
        kelasP.setText("");
        telponP.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit1.setText("");
        tanggalKembali.setDate(new Date());

    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String tanggal = tglinput.format(tanggalKembali.getDate());
        try {
            String sql = "INSERT INTO pengembalian VALUES "
            + "('"+noKembalian.getText()+"','"+noPinjam.getText()+"'"
            + ",'"+nis.getText()+"','"+namaP.getText()+"'"
            + ",'"+kelasP.getText()+"','"+telponP.getText()+"','"
            +kodeBuku.getText()+"','"+judul.getText()+"','"+jenisBuku.getText()+"','"+penerbit1.getText()
            +"','"+tanggal+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Kembali Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Penyimpanan Data Kembali tidak berhasil" );
        }
        noKembalian.setText("");
        noPinjam.setText("");
        nis.setText("");
        namaP.setText("");
        kelasP.setText("");
        telponP.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit1.setText("");
        tanggalKembali.setDate(new Date());
        load_table();
    }//GEN-LAST:event_submitActionPerformed

    private void namaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPActionPerformed

    private void cariPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPinjamActionPerformed
        // TODO add your handling code here:
        tblDaftarPeminjaman tk = new tblDaftarPeminjaman();
        tk.tx = this;
        tk.setVisible(true);
    }//GEN-LAST:event_cariPinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TXTnama;
    private javax.swing.JButton cariPinjam;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jb;
    private javax.swing.JLabel jb1;
    private javax.swing.JTextField jenisBuku;
    private javax.swing.JTextArea judul;
    private javax.swing.JTextField kelasP;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kodeBuku;
    private javax.swing.JTextField namaP;
    private javax.swing.JTextField nis;
    private javax.swing.JTextField noKembalian;
    private javax.swing.JTextField noPinjam;
    private javax.swing.JPanel nomemb;
    private javax.swing.JTextField penerbit1;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JTable tabelPengembalian;
    private com.toedter.calendar.JDateChooser tanggalKembali;
    private javax.swing.JTextField telponP;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        //model.addColumn("No");
        model.addColumn("No Pengembalian");
        model.addColumn("No Peminjaman");
        model.addColumn("Nis");
        model.addColumn("Nama");
        model.addColumn("Kelas");
        model.addColumn("No Telepon");
        model.addColumn("Kode Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Jenis Buku");
        model.addColumn("Penerbit");
        model.addColumn("Tanggal Kembalian");
        
        
        //menampilkan data database kedalam tabel
        try {
            //int no=1;
            String sql = "select * from pengembalian";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),
                res.getString(9),res.getString(10),res.getString(11)});
            }
            tabelPengembalian.setModel(model);
        } catch (Exception e) {
        }
}
}
