
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rizki_
 */
public class member extends javax.swing.JFrame {
    
    SimpleDateFormat tglinput = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat tglview = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form member
     */
    public member() {
        initComponents();
        load_table();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        //
        int x = layar.width / 2 - this.getSize().width/2;
        int y = layar.height / 2 - this.getSize().height/2;
        //
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihan = new javax.swing.ButtonGroup();
        tanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        sub = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        del = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jk1 = new javax.swing.JRadioButton();
        jk2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        notelp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        pencarian = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 550));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Lahir");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));

        sub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/oke.png"))); // NOI18N
        sub.setText("Simpan");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, -1, -1));

        del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/hapus.png"))); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, -1));

        kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/exit.png"))); // NOI18N
        kembali.setText("kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        pilihan.add(jk1);
        jk1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jk1.setText("Laki-laki");
        jk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk1ActionPerformed(evt);
            }
        });
        getContentPane().add(jk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        pilihan.add(jk2);
        jk2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jk2.setText("Perempuan");
        jk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk2ActionPerformed(evt);
            }
        });
        getContentPane().add(jk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No Telp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));
        getContentPane().add(notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Data Member ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kelas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        getContentPane().add(kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 260, 100));

        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nis", "Nama", "Tempat Tanggal Lahir", "Kelas", "Jenis Kelamin", "Alamat", "No Telepon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMemberMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelMember);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 950, 100));

        pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pencarianKeyReleased(evt);
            }
        });
        getContentPane().add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 200, -1));

        cetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/print.png"))); // NOI18N
        cetak.setText("Cetak Kartu");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Cari Nama Berdasarkan NIS ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 180, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
                                               
        // TODO add your handling code here:
        try{
            String NamaFile = "./src/laporan/member.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/newperpustakaan","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            //param.put("nama",pencarian.getText());
            param.put("NIS",pencarian.getText());
            param.put("Nama",pencarian.getText());
                   
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint);
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianKeyReleased
        // TODO add your handling code here:
        String key=pencarian.getText();
        //System.out.println(key);

        if (key!=""){
            cariData(key);
        }else{
            load_table();
        }
    }//GEN-LAST:event_pencarianKeyReleased

    private void tabelMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMemberMouseClicked
        // TODO add your handling code here
        Date dateView = null;
        int bar = tabelMember.rowAtPoint(evt.getPoint());
        String a = tabelMember.getValueAt(bar, 0).toString();
        nis.setText(a);
        String b = tabelMember.getValueAt(bar, 1).toString();
        nama.setText(b);
        try {
        dateView = tglview.parse((String) tabelMember.getValueAt(bar, 2));
        } catch (ParseException ex) {
                Logger.getLogger(member.class.getName()).log(Level.SEVERE, null, ex);
        }
        tanggalLahir.setDate(dateView);
        String d = tabelMember.getValueAt(bar, 3).toString();
        kelas.setText(d);
        String e = tabelMember.getValueAt(bar, 4).toString();
        if(d.equals("Laki-Laki")){jk1.setSelected(true); jk2.setSelected(false);}
        else{jk1.setSelected(false); jk2.setSelected(true);}
        String f = tabelMember.getValueAt(bar, 5).toString();
        alamat.setText(f);
        String g = tabelMember.getValueAt(bar, 6).toString();
        notelp.setText(g);
        
        
        
      
    }//GEN-LAST:event_tabelMemberMouseClicked

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void jk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk2ActionPerformed

    private void jk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk1ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE from member where nis='"+nis.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data telah dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"data gagal dihapus dikarenakan data ini telah dipakai.."
                    + "silakan hapus data di form peminjaman buku.");
        }
        nis.setText("");
        nama.setText("");
        tanggalLahir.setDate(new Date());
        kelas.setText("");
        jk1.setSelected(false);
        jk2.setSelected(false);
        alamat.setText("");
        notelp.setText("");

        load_table();
    }//GEN-LAST:event_delActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(tanggalLahir.getDate()));
        try {
            String sql = "update member set nama=?,tempatTanggalLahir=?,"
            + "kelas=?,jenisKelamin=?,alamat=?,telpon=? where nis=?";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);

            pst.setString(1, nama.getText());
            pst.setString(2, tanggal);
            pst.setString(3, kelas.getText());
            String jkl="";
            if(jk1.isSelected())jkl="Laki-Laki";
            else jkl="Perempuan";
            pst.setString(4, jkl);
            pst.setString(5, alamat.getText());
            pst.setString(6, notelp.getText());
            pst.setString(7, nis.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diupdate");
            //no.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah");
        }
        nis.setText("");
        nama.setText("");
        tanggalLahir.setDate(new Date());
        kelas.setText("");
        jk1.setSelected(false);
        jk2.setSelected(false);
        alamat.setText("");
        notelp.setText("");
        load_table();
    }//GEN-LAST:event_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nis.setText("");
        nama.setText("");
        tanggalLahir.setDate(new Date());
        kelas.setText("");
        jk1.setSelected(false);
        jk2.setSelected(false);
        alamat.setText("");
        notelp.setText("");
    }//GEN-LAST:event_resetActionPerformed

                                      

                           

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        String tanggal = tglinput.format(tanggalLahir.getDate());
        String sql = "INSERT INTO member VALUES (?,?,?,?,?,?,?)";
        try {
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,nis.getText());
            pst.setString(2, nama.getText());
            pst.setString(3, tanggal);
            pst.setString(4, kelas.getText());
            String jkl="";
            if(jk1.isSelected())jkl="Laki-Laki";
            else jkl="Perempuan";
            pst.setString(5, jkl);
            pst.setString(6, alamat.getText());
            pst.setString(7, notelp.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
        }
        nis.setText("");
        nama.setText("");
        tanggalLahir.setDate(new Date());
        kelas.setText("");
        jk1.setSelected(false);
        jk2.setSelected(false);
        alamat.setText("");
        notelp.setText("");

        load_table();
    }//GEN-LAST:event_subActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton cetak;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton jk1;
    private javax.swing.JRadioButton jk2;
    private javax.swing.JTextField kelas;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JTextField notelp;
    private javax.swing.JTextField pencarian;
    private javax.swing.ButtonGroup pilihan;
    private javax.swing.JButton reset;
    private javax.swing.JButton sub;
    private javax.swing.JTable tabelMember;
    private com.toedter.calendar.JDateChooser tanggalLahir;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    private void cariData(String key){
        DefaultTableModel model = new DefaultTableModel();
        //model.addColumn("No");
        model.addColumn("NIS");
        model.addColumn("Nama");
        model.addColumn("Tempat Tanggal Lahir");
        model.addColumn("Kelas");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Telpon");
        try {
            //int no=1;
            String sql = "SELECT * from member where nama LIKE '%"+key+"%' or kelas LIKE '%"+key+"%' or nis LIKE '%"+key+"%'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tabelMember.setModel(model);
        } catch (Exception e) {
        }
        
    }
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        //model.addColumn("No");
        model.addColumn("NIS");
        model.addColumn("Nama");
        model.addColumn("Tempat Tanggal Lahir");
        model.addColumn("Kelas");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Telpon");
        
        
        //menampilkan data database kedalam tabel
        try {
            //int no=1;
            String sql = "SELECT * from member";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tabelMember.setModel(model);
        } catch (Exception e) {
        }
}
}
