
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rizki_
 */
public class pinjam extends javax.swing.JFrame {

    /**
     * Creates new form pinjam
     */
    SimpleDateFormat tglinput = new SimpleDateFormat("yyyy-MM-dd");
    public String NIS,NAMA,KELAS,TELP,KODE,BUKU,JENIS,PENERBIT;
    public String getnis() {
        return NIS;
    }
    public String getnama() {
        return NAMA;
    }
    public String getkelas() {
        return KELAS;
    }
    public String gettelp() {
        return TELP;
    }
    public String getkode() {
        return KODE;
    }
    public String getbuku() {
        return BUKU;
    }
    public String getjenis() {
        return JENIS;
    }
    public String getpenerbit() {
        return PENERBIT;
    }
    public void itemTerpilih(){
    tblDaftarMember tm = new tblDaftarMember();
     tm.tp = this;
     
    nis.setText(NIS);
    nama.setText(NAMA);
    kelas.setText(KELAS);
    telpon.setText(TELP);
}
    public void itemBukuTerpilih(){
    tblDaftarBuku tm = new tblDaftarBuku();
     tm.tb = this;
     
    kodeBuku.setText(KODE);
    judul.setText(BUKU);
    jenisBuku.setText(JENIS);
    penerbit.setText(PENERBIT);
}
    
    public pinjam() {
        initComponents();
        load_table();
        //initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        //
        int x = layar.width / 2 - this.getSize().width/2;
        int y = layar.height / 2 - this.getSize().height/2;
        //
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        pilihan = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        noPeminjaman = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        bt_tambah = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        judul = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        telpon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jenisBuku = new javax.swing.JTextField();
        penerbit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        tanggalPinjam = new com.toedter.calendar.JDateChooser();
        Member = new javax.swing.JButton();
        buku = new javax.swing.JButton();
        nis = new javax.swing.JTextField();
        kodeBuku = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("No Peminjaman");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        getContentPane().add(noPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nis");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Judul buku");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal peminjaman");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 226, -1));

        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/exit.png"))); // NOI18N
        kembali.setText("kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        bt_tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/oke.png"))); // NOI18N
        bt_tambah.setText("Simpan");
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(bt_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/hapus.png"))); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        judul.setColumns(20);
        judul.setRows(5);
        jScrollPane2.setViewportView(judul);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 230, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Penerbit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kelas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));
        getContentPane().add(kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 112, -1));
        getContentPane().add(telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 141, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("No Telp");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jenis Buku");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));
        getContentPane().add(jenisBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 173, -1));
        getContentPane().add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 197, -1));

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Peminjaman", "Nis", "Nama", "Kelas", "No Telp", "Kode Buku", "Judul Buku", "Jenis Buku", "Penerbit", "tanggal Peminjaman"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 950, 146));
        getContentPane().add(tanggalPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 210, -1));

        Member.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/cari.png"))); // NOI18N
        Member.setText("Cari");
        Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberActionPerformed(evt);
            }
        });
        getContentPane().add(Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        buku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/cari.png"))); // NOI18N
        buku.setText("Cari");
        buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuActionPerformed(evt);
            }
        });
        getContentPane().add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisActionPerformed(evt);
            }
        });
        getContentPane().add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, -1));
        getContentPane().add(kodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nama");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Kode Buku");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Data Peminjaman Buku ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        String tanggal = tglinput.format(tanggalPinjam.getDate());
        String sql = "INSERT INTO peminjaman VALUES (?,?,?,?,?,?,?,?,?,?)"; 
        try {                    
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1, noPeminjaman.getText());
            pst.setString(2, nis.getText());
            pst.setString(3, nama.getText());
            pst.setString(4, kelas.getText());
            pst.setString(5, telpon.getText());
            pst.setString(6, kodeBuku.getText());
            pst.setString(7, judul.getText());
            pst.setString(8, jenisBuku.getText());
            pst.setString(9, penerbit.getText());
            pst.setString(10, tanggal);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
        }
        noPeminjaman.setText("");
        nis.setText("");
        nama.setText("");
        kelas.setText("");
        telpon.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit.setText("");
        tanggalPinjam.setDate(new Date());
        //w_kembali.setText("");
        load_table();
        //initComponents();
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        noPeminjaman.setText("");
        nis.setText("");
        nama.setText("");
        kelas.setText("");
        telpon.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit.setText("");
        tanggalPinjam.setDate(new Date());
    }//GEN-LAST:event_resetActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "DELETE from peminjaman where "
                    + "noPeminjaman='"+noPeminjaman.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data telah dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"data gagal dihapus dikarenakan data ini telah dipakai.."
                    + "silakan hapus data di form pengembalian buku.");
        }
        noPeminjaman.setText("");
        nis.setText("");
        nama.setText("");
        kelas.setText("");
        telpon.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit.setText("");
        tanggalPinjam.setDate(new Date());
        load_table();
    }//GEN-LAST:event_delActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String tanggal = tglinput.format(tanggalPinjam.getDate());
        try {
            String sql ="UPDATE peminjaman SET nis = '"+nis.getText()+"', "
                    + "nama = '"+nama.getText()+"', "
                    + "kelas = '"+kelas.getText()+"', "
                    + "telepon = '"+telpon.getText()+"',"
                    + "kode = '"+kodeBuku.getText()+"', "
                    + "buku= '"+judul.getText()+"',"
                    + "jenisBuku= '"+jenisBuku.getText()+"',"
                    + "penerbit= '"+penerbit.getText()+"',"
                    + "tanggalPeminjaman= '"+tanggal+"' "
                    + "WHERE noPeminjaman = '"+noPeminjaman.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diupdate");
            //no.requestFocus();
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah");
            }
       noPeminjaman.setText("");
        nis.setText("");
        nama.setText("");
        kelas.setText("");
        telpon.setText("");
        kodeBuku.setText("");
        judul.setText("");
        jenisBuku.setText("");
        penerbit.setText("");
        tanggalPinjam.setDate(new Date());
        load_table();
    }//GEN-LAST:event_updateActionPerformed

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        // TODO add your handling code here:
        Date dateView = null;
        int bar = tabelPeminjaman.rowAtPoint(evt.getPoint());
        String a = tabelPeminjaman.getValueAt(bar, 0).toString();
        noPeminjaman.setText(a);
        String b = tabelPeminjaman.getValueAt(bar, 1).toString();
        nis.setText(b);
        String c = tabelPeminjaman.getValueAt(bar, 2).toString();
        nama.setText(c);
        String d = tabelPeminjaman.getValueAt(bar, 3).toString();
        kelas.setText(d);
        String e = tabelPeminjaman.getValueAt(bar, 4).toString();
        telpon.setText(e);
        String f = tabelPeminjaman.getValueAt(bar, 5).toString();
        kodeBuku.setText(f);
        String g = tabelPeminjaman.getValueAt(bar, 6).toString();
        judul.setText(g);
        String h = tabelPeminjaman.getValueAt(bar, 7).toString();
        jenisBuku.setText(h);
        String i = tabelPeminjaman.getValueAt(bar, 8).toString();
        penerbit.setText(i);
         try {
        dateView = tglinput.parse((String) tabelPeminjaman.getValueAt(bar, 9));
        } catch (ParseException ex) {
                Logger.getLogger(member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisActionPerformed

    private void MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberActionPerformed
        // TODO add your handling code here:
        tblDaftarMember tm = new tblDaftarMember();
        tm.tp = this;
        tm.setVisible(true);
    }//GEN-LAST:event_MemberActionPerformed

    private void bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuActionPerformed
        // TODO add your handling code here:
        tblDaftarBuku tm = new tblDaftarBuku();
        tm.tb = this;
        tm.setVisible(true);
    }//GEN-LAST:event_bukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Member;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton buku;
    private javax.swing.JButton del;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jenisBuku;
    public javax.swing.JTextArea judul;
    public javax.swing.JTextField kelas;
    private javax.swing.JButton kembali;
    public javax.swing.JTextField kodeBuku;
    public javax.swing.JTextField nama;
    public javax.swing.JTextField nis;
    private javax.swing.JTextField noPeminjaman;
    public javax.swing.JTextField penerbit;
    private javax.swing.ButtonGroup pilihan;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabelPeminjaman;
    private com.toedter.calendar.JDateChooser tanggalPinjam;
    public javax.swing.JTextField telpon;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        //model.addColumn("No");
        model.addColumn("No Peminjaman");
        model.addColumn("Nis");
        model.addColumn("Nama");
        model.addColumn("Kelas");
        model.addColumn("No Telp");
        model.addColumn("Kode Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Jenis Buku");
        model.addColumn("Penerbit");
        model.addColumn("Tanggal Pinjam");
        //model.addColumn("Tanggal Kembali");
        
        
        //menampilkan data database kedalam tabel
        try {
            //int no=1;
            String sql = "select * from peminjaman";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)
                        ,res.getString(4),res.getString(5),res.getString(6),res.getString(7)
                        ,res.getString(8),res.getString(9),res.getString(10)});
            }
            tabelPeminjaman.setModel(model);
        } catch (Exception e) {
        }
}
}
